version: '3.9'

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.12.0
    container_name: wazuh.manager
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    restart: unless-stopped
    volumes:
      - wazuh_data:/var/ossec/data

volumes:
  wazuh_data:
