version: "3.9"

services:
  pc1:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pc1
    networks:
      laboratorio_vlan10:
        ipv4_address: 10.100.10.10

  pc2:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pc2
    networks:
      laboratorio_vlan20:
        ipv4_address: 10.100.20.10

  pc3:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pc3
    networks:
      laboratorio_vlan30:
        ipv4_address: 10.100.30.10

  pc4:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pc4
    networks:
      laboratorio_vlan40:
        ipv4_address: 10.100.40.10

  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    container_name: laboratorio-router
    cap_add:
      - NET_ADMIN
    command: /entrypoint.sh
    networks:
      laboratorio_vlan10:
        ipv4_address: 10.100.10.2
      laboratorio_vlan20:
        ipv4_address: 10.100.20.2
      laboratorio_vlan30:
        ipv4_address: 10.100.30.2
      laboratorio_vlan40:
        ipv4_address: 10.100.40.2

networks:
  laboratorio_vlan10:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.10.0/26

  laboratorio_vlan20:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.20.0/26

  laboratorio_vlan30:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.30.0/26

  laboratorio_vlan40:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.40.0/26
