apiVersion: 1
groups:
  - orgId: 1
    name: api-alerts
    folder: "Secure API"       # <-- requerido
    interval: 1m
    rules:
      - uid: high_5xx_rate
        title: Alta tasa de 5xx
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus_ds
            relativeTimeRange: { from: 300, to: 0 }
            model:
              expr: sum(rate(http_requests_total{status=~"5.."}[5m]))
              instant: false
              interval: ""
              legendFormat: ""
              refId: A
        for: 5m
        labels: { severity: "high" }
        annotations:
          summary: "Errores 5xx altos en los últimos 5m"
        isPaused: false
