services:

  # ======================
  # ROUTER / FIREWALL
  # ======================
  router:
    image: alpine
    container_name: router
    command: ["sh", "-c", "apk add iptables iproute2 iputils && sleep infinity"]
    privileged: true
    networks:
      vlan10:
        ipv4_address: 192.168.110.254

  # ======================
  # CLIENTES VLAN 10 (ADMINISTRACIÓN)
  # ======================
  admin_pc:
    image: alpine
    container_name: admin_pc
    command: ["sh", "-c", "apk add iputils && sleep infinity"]
    networks:
      vlan10:
        ipv4_address: 192.168.110.10

  # ======================
  # CLIENTES VLAN 20 (DESARROLLO)
  # ======================
  dev_pc:
    image: alpine
    container_name: dev_pc
    command: ["sh", "-c", "apk add iputils && sleep infinity"]
    networks:
      vlan20:
        ipv4_address: 192.168.120.10

  # ======================
  # CLIENTES VLAN 30 (SOPORTE TÉCNICO)
  # ======================
  support_pc:
    image: alpine
    container_name: support_pc
    command: ["sh", "-c", "apk add iputils && sleep infinity"]
    networks:
      vlan30:
        ipv4_address: 192.168.130.10

  # ======================
  # SERVIDOR INTERNO VLAN 40
  # ======================
  server:
    image: alpine
    container_name: internal_server
    command: ["sh", "-c", "apk add iputils && sleep infinity"]
    networks:
      vlan40:
        ipv4_address: 192.168.140.10

# ======================
# DEFINICIÓN DE VLANs (Redes bridge de Docker)
# ======================
networks:
  vlan10:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.110.0/24

  vlan20:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.120.0/24

  vlan30:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.130.0/24

  vlan40:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.140.0/24
