services:
  kali:
    image: kalilinux/kali-rolling
    container_name: kali_pentest_box
    privileged: true
    tty: true
    stdin_open: true
    network_mode: host
    volumes:
      - ./kali-data:/root
